# Generated by Django 6.0.6 on 2026-06-26 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel', models.FloatField()),
                ('electricity', models.FloatField()),
                ('diet', models.CharField(default='Vegetarian', max_length=50)),
                ('waste', models.FloatField(default=0)),
                ('water', models.FloatField(default=0)),
                ('carbon_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carbon_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
